### ISSUE TITLE
"Failed to restore message"

### ISSUE THREAD

**Issue by justanotheranonymoususer** [tomer8007/whatsapp-web-incognito#146]
Looks like it's no longer able to restore deleted message

![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/5781692/d9cab414-9d74-4cb2-bbb6-dfbcc7b6b3eb)

**Comment by tomer8007** [comment]
It seems WhatsApp made the XMPP acknowledgments mechanism more robust and added something called LID. Looking. I can get restored messages when they get deleted while the WhatsApp window is open, though.

**Comment by tomer8007** [comment]
OK, I committed a8ff5fc47bdbc82f1fe16b5218c633d41ccbe214 which seems to make the message restore feature work fine for me now. Please let me know if this changes stuff for you too.

**Comment by justanotheranonymoususer** [comment]
Still doesn't work for me sadly. ver 2.1.0, does it contain the fix?

**Comment by tomer8007** [comment]
It should :-(
Javascript errors? Also I'm talking about the restore of new messages, of course.

**Comment by justanotheranonymoususer** [comment]
> Also I'm talking about the restore of new messages, of course.

yes sure

lots of errors:

![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/5781692/fff34e7a-a563-4861-a3ef-b5b1b9217ce8)

**Comment by tomer8007** [comment]
Ah, I see. I hope to encounter this error in the upcoming days. If you feel like debugging in the meantime you can enable `WAdebug = true` and try to see for yourself if the revoke message is really the one that fails decryption.

**Comment by justanotheranonymoususer** [comment]
It stops here on every msg I receive. Not sure what else I can debug, lmk.
![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/5781692/9d4f3a00-8b25-4b0a-933f-4c52c6176a57)

**Comment by tomer8007** [comment]
Does the `cannot convert undefined or null to object` exception happen for messages from all contacts/groups? Did you try other accounts/re-logging in? I ask because for me it works.

**Comment by justanotheranonymoususer** [comment]
> Does the Cannot convert undefined or null to object exception happen for messages from all contacts/groups?

Yes, seems like it

> Did you try other accounts/re-logging in? I ask because for me it works.

I don't have other accounts, cleared all data of web.whatsapp.com and logged in from start but same errors still

**Comment by aviv926** [comment]
Is there any new information about this? For me it doesn't even show the message `Failed to restore message`

**Comment by tomer8007** [comment]
@aviv926 Sadly there is no new information because this feature works for me. I also tried with WA Web Plus enabled too. Thanks for the warm words though

**Comment by aviv926** [comment]
> @aviv926 Sadly there is no new information because this feature works for me. I also tried with WA Web Plus enabled too. Thanks for the warm words though
> 
> Do you get the same error as @justanotheranonymoususer ?

This might not be such a smart question on my part, but are you using the published version in the repository here? I'm assuming you're using git so I guess this question doesn't make much sense.

 thank you for the answer

**Comment by justanotheranonymoususer** [comment]
I've installed it from the extension store, not from the repo

**Comment by tomer8007** [comment]
I'm using the version from the git repository.

**Comment by aviv926** [comment]
> I'm using the version from the git repository.

I seem to have figured out what the problem is
When the WhatsApp interface is in a language other than English, the message "Failed to restore messages" is not displayed as soon as you change the language to English, the message "Failed to restore messages" is displayed but is not yet restored

Could you please specify what your definition is?
What language interface?
And what is the version of your WhatsApp?
Also are you running the extension on chrome?

It is important for me to note that in previous versions it worked without a problem with a system interface that is not English
Thanks

**Comment by tomer8007** [comment]
I tested it on both English and non-english setups, and yes, I'm using chrome. However I just encountered the following error which I think is the same error you're getting:

![image](https://github.com/tomer8007/whatsapp-web-incognito/assets/11458759/966649cd-363e-45b3-8591-213f9ca4d454)

**Comment by aviv926** [comment]
> I tested it on both English and non-english setups, and yes, I'm using chrome. However I just encountered the following error which I think is the same error you're getting:
> 
> ![image](https://user-images.githubusercontent.com/11458759/276499870-966649cd-363e-45b3-8591-213f9ca4d454.png)

Does this mean there is a problem with the extension? Or does it have nothing to do with it and the problem is on my side and not in the extension?
Sorry, I didn't quite understand

**Comment by tomer8007** [comment]
@aviv926 @justanotheranonymoususer Can you tell if the newer version fixes the restore of messages?

**Comment by justanotheranonymoususer** [comment]
Yes it seems to be working now, thanks! FWIW there are still errors in the
console from interception.js:710, not sure if it's a real problem

**Comment by tomer8007** [comment]
OK, if it looks like a real problem you can open another issue for it
