### ISSUE TITLE
WAIncognito is temporarily broken

### ISSUE THREAD

**Issue by Peter-maximus** [tomer8007/whatsapp-web-incognito#193]
Whatsapp Web version: 2.3000.1022594794
WAIncognito version: 2.2.4

![Image](https://github.com/user-attachments/assets/f03f0da8-46e7-4264-8314-e3fa841fad91)

**Comment by Revasz** [comment]
Same issue on my end.

Edge: v136.0.3240.50
Whatsapp Web version: v2.3000.1022593743
WAIncognito version: v2.2.4

**Comment by tomer8007** [comment]
I pushed version 2.2.5, which should try to support both GUI versions. @Revasz @Peter-maximus Please let me know if this version works for you.

**Comment by Peter-maximus** [comment]
how long does it take to populate to webstore? currently it is still shows 2.2.4

**Comment by tomer8007** [comment]
@Peter-maximus Whoops, I got it wrong in 2.2.5. I now uploaded 2.2.5 instead. It should be live in the store in a few days. You can test it now with this file:

[WhatsApp Web Incognito.zip](https://github.com/user-attachments/files/20091401/WhatsApp.Web.Incognito.zip)

**Comment by Revasz** [comment]
I received the updated version today and the issue is gone.
Everything is working as expected again, on my end.

Thank you.

**Comment by Peter-maximus** [comment]
same for me. thx a lot.
